image: "debian:9"

variables:
  APT: apt-get $APT_FLAGS
  APT_FLAGS: -q -y --no-install-recommends
  DEBIAN_FRONTEND: noninteractive
  PATH: "~/.cask/bin:$PATH"

test:
  stage: test
  script:
    - $APT update
    - $APT install build-essential curl emacs25 python
    - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
    - make
